name: hexlet ci app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm' # ускоряет повторные сборки
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # Ставим зависимости
      - run: npm install
      # Продолжаем setup
      - run: npm run build
      # Запускаем линтер
      - run: npx eslint
      # Запускаем тесты
      - name: run tests
        run: npm test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
