name: hexlet ci app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      ## Делаем setup
      # Ставим зависимости
      - run: npm install
      # Продолжаем setup
      - run: npm run build
      # Запускаем линтер
      - run: npm run lint
      # Запускаем тесты
      - name: run tests
        run: npm test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
